jobs:
  build:
    name: Build
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4.1.1
    - continue-on-error: true
      name: Set up JDK ${{ matrix.java-version }}
      uses: actions/setup-java@v4
      with:
        cache: gradle
        distribution: zulu
        java-version: ${{ matrix.java-version }}
    - continue-on-error: true
      name: Build with Gradle
      run: ./gradlew build buildDeb buildRpm
    - continue-on-error: true
      name: Upload allure-commandline artifact
      uses: actions/upload-artifact@v4
      with:
        name: allure-commandline
        path: allure-commandline/build/install/allure-commandline
    - continue-on-error: true
      name: Upload allure-results artifact
      uses: actions/upload-artifact@v4
      with:
        name: allure-results
        path: allure-generator/test-data/demo2
    strategy:
      fail-fast: false
      matrix:
        java-version:
        - '17'
  testcmd:
    name: Test Allure Commandline
    needs: build
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Set up JRE ${{ matrix.java-version }}
      uses: actions/setup-java@v4
      with:
        distribution: zulu
        java-package: jre
        java-version: ${{ matrix.java-version }}
    - continue-on-error: true
      name: Download allure-commandline artifact
      uses: actions/download-artifact@v4
      with:
        name: allure-commandline
    - continue-on-error: true
      name: Download allure-results artifact
      uses: actions/download-artifact@v4
      with:
        name: allure-results
        path: allure-results
    - continue-on-error: true
      name: Add execute permissions to script
      run: chmod +x ./bin/allure
    - continue-on-error: true
      name: Run version command
      run: ./bin/allure --version
    - continue-on-error: true
      name: Generate demo report
      run: ./bin/allure generate allure-results
    strategy:
      fail-fast: false
      matrix:
        java-version:
        - '8'
        - '11'
        - '17'
        - '20'
name: Build
on:
  repository_dispatch:
    types: trigger-ga___build.yaml
