jobs:
  triage:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/labeler@v4
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
name: Set theme labels
on:
  repository_dispatch:
    types: trigger-ga___labeler.yml
