jobs:
  triage:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Check release version
      run: 'expr "${{ github.event.inputs.releaseVersion }}" : ''[[:digit:]][[:digit:]]*\.[[:digit:]][[:digit:]]*\.[[:digit:]][[:digit:]]*$''

        '
    - continue-on-error: true
      name: Check next version
      run: 'expr "${{ github.event.inputs.nextVersion }}" : ''[[:digit:]][[:digit:]]*\.[[:digit:]][[:digit:]]*$''

        '
    - continue-on-error: true
      uses: actions/checkout@v4.1.1
      with:
        token: ${{ secrets.QAMETA_CI }}
    - continue-on-error: true
      name: Configure CI Git User
      run: 'git config --global user.name qameta-ci

        git config --global user.email qameta-ci@qameta.io

        '
    - continue-on-error: true
      name: Set release version
      run: 'sed -i -e ''/version=/s/.*/version=${{ github.event.inputs.releaseVersion
        }}/g'' gradle.properties

        cat gradle.properties

        '
    - continue-on-error: true
      name: Commit release version and create tag
      run: 'git commit -am "release ${{ github.event.inputs.releaseVersion }}"

        git tag ${{ github.event.inputs.releaseVersion }}

        git push origin ${{ github.event.inputs.releaseVersion }}

        '
    - continue-on-error: true
      name: Set next development version
      run: 'sed -i -e ''/version=/s/.*/version=${{ github.event.inputs.nextVersion
        }}-SNAPSHOT/g'' gradle.properties

        cat gradle.properties

        '
    - continue-on-error: true
      name: Commit next development version and push it
      run: 'git commit -am "set next development version ${{ github.event.inputs.nextVersion
        }}"

        git push origin ${{ github.ref }}

        '
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.QAMETA_CI }}
      name: Publish Github Release
      uses: octokit/request-action@v2.x
      with:
        generate_release_notes: true
        route: POST /repos/${{ github.repository }}/releases
        tag_name: ${{ github.event.inputs.releaseVersion }}
        target_commitish: ${{ github.ref }}
name: Release
on:
  repository_dispatch:
    types: trigger-ga___release.yaml
run-name: Release ${{ inputs.releaseVersion }} (next ${{ inputs.nextVersion }}) by
  ${{ github.actor }}
